name: Audio Processing (Beta)

on:
  pull_request:
    branches:
      - main

jobs:
  process-audio:
    runs-on: ubuntu-latest
    env:
      S3_PREFIX: beta/
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14
      - name: Install dependencies
        run: pip install boto3 requests
      - name: Run processing script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: python process_audio.py
